### PR TITLE
make make_reg_string work when the error output contains unicode characters

### LINKED ISSUE #19: Regexp generation fails when unicode is involved
If the error we are looking for contains unicode, regexp generation fails real bad:

```
I think the error is 'Error: No such bound variable φ (possible names are: E3, E4, φ0, Q0, e2 and
σ2).
'.
The corresponding regular expression is 'File "[^"]+", line ([0-9]+), characters [0-9-]+:
(Error\:\ No\ such\ bound\ variable\ \�\�\ \(possible\ names\ are\:\ E[\d]+\,\ E[\d]+\,\ \�\�[\d]+\,\ Q[\d]+\,\ e[\d]+\ and\
\�\�[\d]+\)\.)'.
```

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes #19.

This is the lazy solution, not converting the entire program to properly use unicode everywhere - hence the string is encoded again before being returned. If this is not done, every time this string is printed, it would try to encode it as `'ascii'` which does not work.

### CODE REVIEW

**Comment by JasonGross** [comment]
Thanks!  Two concerns, before I merge:
1. Does this play well with the fact that (older versions of?) coqtop in emacs mode sometimes emits characters which are not valid utf8 (to delimit warnings, if I recall correctly)?  (I think yes, but I haven't tested it, and I remember having trouble with Proviola when it wanted all of Coq's output to be valid Unicode.)
2. Could I get you to submit an example for the examples directory to be tested on Travis?  If this is too much work for a small change, I'm also happy to do this bit myself.  You can model it off of example_10.

**Comment by RalfJung** [comment]
1. I have absolutely no idea if this still happens, or how I could test this. The code will probably throw an exception if the utf-8 decoding fails.
2. Sure, I can add a testcase, sure. Well, I can try ;-) there is no "make check", as far as I can tell, and the different example bash scripts show vastly different behavior when I call them manually.

**Comment by RalfJung** [comment]
I created an example. It does "something" when run. But whether that means that it fails or succeeds, I cannot tell from all the noise it prints.

**Comment by JasonGross** [comment]
Urg, yeah, I'll go make a make check target and add a read me to the examples folder.  In the meantime, add a line to .travis.yml to ruin this example?

**Comment by JasonGross** [comment]
The idea is that if you run `yes "y" | ./run-example-n.sh`, the exit code should tell you whether it succeeded or failed.

**Comment by JasonGross** [comment]
> The script didn't error previously, either. It just gave me a really bad regexp.

The script will complain if the regexp it gives you doesn't match the actual error message.  So is this just to fix the display of the regular expression?

**Comment by RalfJung** [comment]
> The script will complain if the regexp it gives you doesn't match the actual error message. So is this just to fix the display of the regular expression?

I cannot imagine that it matched. The regexp separated the two bytes of the utf-8 multi-byte character...

I will try to pattern-match the travis file. I never used that stuff myself ;-)

File: examples/run-example-11.sh [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    echo
+    echo
+    echo
+    echo "Actual:"
+    echo "$ACTUAL_PRE"
+    exit 1
+fi
+
+python ../../find-bug.py example_11.v bug_11.v || exit $?
+EXPECTED='^(\* File reduced by coq-bug-finder from original input, then from [0-9]\+ lines to [0-9]\+ lines, then from [0-9]\+ lines to [0-9]\+ lines, then from [0-9]\+ lines to [0-9]\+ lines \*)$'
```
Comment (JasonGross) [inline examples/run-example-11.sh]: If you remove lines 21 and below (which I'm pretty sure won't function correctly), I'll merge this PR.

**Comment by RalfJung** [comment]
Deal ;-)

**Comment by JasonGross** [comment]
Thanks!  And sorry for all the back-and-forth for such a small change.

**Comment by RalfJung** [comment]
I don't mind. Actually, I appreciate to see you care about testcases :)
